services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    expose:
      - "3000" # Expose port internally to Nginx
    restart: always

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - app
    restart: always
    entrypoint: [ "/docker-entrypoint.sh", "nginx", "-g", "daemon off;" ]

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /var/www/certbot:/var/www/certbot
    entrypoint: |
      /bin/sh -c '
      DOMAIN="next-basic.cloudfor.fun"
      EMAIL="matiasbaldanza.donweb@gmail.com"
      WEBROOT="/var/www/certbot"

      # Check if the certificate already exists
      if [ ! -f "/etc/letsencrypt/live/$$DOMAIN/fullchain.pem" ]; then
        echo "No existing certificate found. Requesting a new one..."
        certbot certonly --non-interactive --agree-tos --email $$EMAIL \
          --webroot -w $$WEBROOT -d $$DOMAIN
      fi

      # Renewal loop
      while :; do
        echo "Checking for certificate renewal..."
        certbot renew --webroot -w "$$WEBROOT"
        echo "Certbot renewal process completed."
        sleep 12h
      done
      '
    depends_on:
      - nginx
    restart: always
