services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    expose:
      - "3000" # Expose port internally to Nginx
    restart: always

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app
    restart: always
